# Generated by Django 5.1.1 on 2024-09-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datemodel',
            name='date',
            field=models.CharField(blank=True, default='00000', max_length=21),
        ),
    ]
