# Generated by Django 5.1.1 on 2024-09-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_datemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datemodel',
            name='date',
            field=models.CharField(blank=True, max_length=21),
        ),
    ]
