# Generated by Django 5.1.1 on 2024-09-18 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_alter_datemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showdatamodel',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parser.filemodel'),
        ),
        migrations.AlterField(
            model_name='statisticsmodel',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parser.filemodel'),
        ),
    ]
