# Generated by Django 5.1.1 on 2024-09-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_alter_showdatamodel_file_alter_statisticsmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='showdatamodel',
            name='is_check',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
