# Generated by Django 5.1.1 on 2024-09-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_showdatamodel_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='showdatamodel',
            name='is_showing',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
