# Generated by Django 5.1.1 on 2024-09-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_showdatamodel_is_showing'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsmodel',
            name='count_domains',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='count_shop_store_domains',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
