# Generated by Django 5.1.1 on 2024-09-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0007_statisticsmodel_count_domains_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('domain', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='showdatamodel',
            name='status',
            field=models.CharField(choices=[('GOOD', 'Успешно спаршено'), ('BAD', 'Невозможно спрасить'), ('AGAIN', 'Отправлено на перепроверку')], max_length=5, null=True),
        ),
    ]
