# Generated by Django 5.1.1 on 2024-09-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0008_uploaddatamodel_showdatamodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showdatamodel',
            name='file',
        ),
    ]
