# Generated by Django 5.1.1 on 2024-09-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0009_remove_showdatamodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='file',
        ),
    ]
