# Generated by Django 5.1.1 on 2024-09-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0010_remove_statisticsmodel_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgainDataModel',
        ),
        migrations.DeleteModel(
            name='ShowDataModel',
        ),
        migrations.AddField(
            model_name='uploaddatamodel',
            name='domain_for_parsing',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploaddatamodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='uploaddatamodel',
            name='inn',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='uploaddatamodel',
            name='ip',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='uploaddatamodel',
            name='is_check',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='uploaddatamodel',
            name='is_showing',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='uploaddatamodel',
            name='ooo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='uploaddatamodel',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uploaddatamodel',
            name='status',
            field=models.CharField(choices=[('GOOD', 'Успешно спаршено'), ('BAD', 'Невозможно спрасить'), ('AGAIN', 'Отправлено на перепроверку')], max_length=5, null=True),
        ),
    ]
