# Generated by Django 5.1.1 on 2024-09-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0011_delete_againdatamodel_delete_showdatamodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatamodel',
            name='status',
            field=models.CharField(choices=[('GOOD', 'Успешно спаршено'), ('BAD', 'Невозможно спрасить'), ('AGAIN', 'Отправлено на перепроверку'), ('NTH', 'Файл пока что только загружен')], max_length=5, null=True),
        ),
    ]
