# Generated by Django 5.1.1 on 2024-09-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0012_alter_uploaddatamodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatamodel',
            name='inn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uploaddatamodel',
            name='phone',
            field=models.TextField(null=True),
        ),
    ]
