# Generated by Django 5.1.1 on 2024-09-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0013_alter_uploaddatamodel_inn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsmodel',
            name='status',
            field=models.CharField(choices=[('FULL', 'Последняя фулл проверка'), ('AGAINDATA', 'Последняя перепроверка')], max_length=9, null=True),
        ),
    ]
