# Generated by Django 5.1.1 on 2024-09-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0014_statisticsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatamodel',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
