# Generated by Django 5.1.1 on 2024-09-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0015_alter_uploaddatamodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatamodel',
            name='status',
            field=models.CharField(choices=[('GOOD', 'Успешно спаршено'), ('BAD', 'Невозможно спрасить'), ('AGAIN', 'Отправлено на перепроверку'), ('NTH', 'Файл пока что только загружен'), ('DEL', 'Удалили самостоятельно')], max_length=5, null=True),
        ),
    ]
