# Generated by Django 5.1.1 on 2024-09-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0016_alter_uploaddatamodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddatamodel',
            name='status_good',
            field=models.CharField(choices=[('TAKE', 'Берем в работу'), ('ALREADY', 'Уже есть договор'), ('NOTNEED', 'Договор не нужен'), ('DOESNOT', 'Не подходит')], max_length=7, null=True),
        ),
    ]
