# Generated by Django 5.1.1 on 2025-01-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0018_uploaddatamodel_it_was_good'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateForCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NTH', 'Даты загружены, но не спаршены'), ('SCF', 'Даты спаршены')], default='NTH', max_length=5, null=True)),
                ('date', models.TextField()),
            ],
        ),
    ]
